version: "3.9"

services:
  tg-bot:
    build: .
    image: ${DOCKERHUB_USER:-local}/tg-chat-bot:latest
    container_name: tg-chat-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs

