# -*- coding: utf-8 -*-
"""Сопоставление стран и валют для проверки через API."""

# Страна (название, нижний регистр) -> код валюты (ISO 4217)
COUNTRY_TO_CURRENCY = {
    "россия": "RUB",
    "russia": "RUB",
    "рф": "RUB",
    "сша": "USD",
    "америка": "USD",
    "usa": "USD",
    "us": "USD",
    "united states": "USD",
    "китай": "CNY",
    "china": "CNY",
    "европа": "EUR",
    "евросоюз": "EUR",
    "германия": "EUR",
    "germany": "EUR",
    "франция": "EUR",
    "france": "EUR",
    "италия": "EUR",
    "italy": "EUR",
    "испания": "EUR",
    "spain": "EUR",
    "eur": "EUR",
    "великобритания": "GBP",
    "англия": "GBP",
    "uk": "GBP",
    "gb": "GBP",
    "united kingdom": "GBP",
    "britain": "GBP",
    "турция": "TRY",
    "turkey": "TRY",
    "таиланд": "THB",
    "thailand": "THB",
    "вьетнам": "VND",
    "vietnam": "VND",
    "индонезия": "IDR",
    "indonesia": "IDR",
    "япония": "JPY",
    "japan": "JPY",
    "индия": "INR",
    "india": "INR",
    "оаэ": "AED",
    "дубай": "AED",
    "uae": "AED",
    "egypt": "EGP",
    "египет": "EGP",
    "швейцария": "CHF",
    "switzerland": "CHF",
    "казахстан": "KZT",
    "kazakhstan": "KZT",
    "беларусь": "BYN",
    "belarus": "BYN",
    "украина": "UAH",
    "ukraine": "UAH",
    "грузия": "GEL",
    "georgia": "GEL",
    "армения": "AMD",
    "armenia": "AMD",
    "азербайджан": "AZN",
    "azerbaijan": "AZN",
    "узбекистан": "UZS",
    "uzbekistan": "UZS",
    "туркменистан": "TMT",
    "turkmenistan": "TMT",
    "корея": "KRW",
    "южная корея": "KRW",
    "south korea": "KRW",
    "korea": "KRW",
    "австралия": "AUD",
    "australia": "AUD",
    "канада": "CAD",
    "canada": "CAD",
    "бразилия": "BRL",
    "brazil": "BRL",
    "мексика": "MXN",
    "mexico": "MXN",
    "аргентина": "ARS",
    "argentina": "ARS",
    "чехия": "CZK",
    "czech": "CZK",
    "польша": "PLN",
    "poland": "PLN",
    "венгрия": "HUF",
    "hungary": "HUF",
    "румыния": "RON",
    "romania": "RON",
    "болгария": "BGN",
    "bulgaria": "BGN",
    "греция": "EUR",
    "greece": "EUR",
    "хорватия": "EUR",
    "croatia": "EUR",
    "сербия": "RSD",
    "serbia": "RSD",
    "черногория": "EUR",
    "montenegro": "EUR",
    "албания": "ALL",
    "albania": "ALL",
    "мальдивы": "MVR",
    "maldives": "MVR",
    "шри-ланка": "LKR",
    "sri lanka": "LKR",
    "филиппины": "PHP",
    "philippines": "PHP",
    "малайзия": "MYR",
    "malaysia": "MYR",
    "сингапур": "SGD",
    "singapore": "SGD",
    "гонконг": "HKD",
    "hong kong": "HKD",
    "тайвань": "TWD",
    "taiwan": "TWD",
    "новая зеландия": "NZD",
    "new zealand": "NZD",
    "юар": "ZAR",
    "south africa": "ZAR",
    "израиль": "ILS",
    "israel": "ILS",
    "марокко": "MAD",
    "morocco": "MAD",
    "тунис": "TND",
    "tunisia": "TND",
}


def country_to_currency(country: str) -> str | None:
    """Возвращает код валюты по названию страны или None."""
    key = (country or "").strip().lower()
    return COUNTRY_TO_CURRENCY.get(key)
